<a href="https://colab.research.google.com/github/ali-talebi/Csite/blob/create-branch-data/create_database_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [2]:
def GET_DATA_WITH_LINK_FUNC(url) :
    response = requests.get(url)
    status_code = response.status_code

    soup = BeautifulSoup(response.text, 'html.parser')
    links = soup.find_all('a')
    a_link = []
    for link in links:
        try:
            new_link = ''
            url_ = link.get('href')
            if len(url_) > 1 :

                if url_[0] in ['#' , ':'  , '' , '?' ] or '.html' in  url_ :
                    continue

                elif url_[0] == '/' :
                    if url[-1] == '/' :
                        url = url[0:-1]
                    new_link = url + url_
                    a_link.append(new_link)


            elif 'https' in url_ or 'http' in url_ :
                new_link = url_

                a_link.append(new_link)

        except Exception as e:
            pass





    s_  = ""
    p_tags = soup.find_all('p')
    for p_tag in p_tags:
        p_text = p_tag.get_text(strip=True)
        a_tags = p_tag.find_all('a')
        a_texts = [a_tag.get_text(strip=True) for a_tag in a_tags]
        p_link_a = ', '.join(a_texts)
        p_tag.append(p_text)
        p_tag.append(p_link_a)
        s_ += p_text
        s_ += p_link_a


    server_name = " "
    if response.headers['server'] :
        server_name = response.headers['server']


    return status_code , a_link , s_ , server_name

In [3]:
list_site_path = "/content/drive/MyDrive/project_zamani_sohrevardi/tranco_W8L29.csv"
dataset = pd.read_csv( list_site_path , header = None )
dataset.columns =  ['index' , 'domain']
dataset.drop(['index'] , axis = 1 , inplace=True )

In [4]:
dataset

                   domain
0              google.com
1            a-msedge.net
2           microsoft.com
3            facebook.com
4           amazonaws.com
...                   ...
999995   smartwebwise.com
999996  smartwheels.autos
999997     smashkaart.com
999998     smb-service.kr
999999           smhrc.kr

[1000000 rows x 1 columns]

In [19]:
get_data = {'domain':[] , 'get_tex':[]}

In [20]:

for domain in dataset.iloc[: 500 , 0 ] :
  if "https://" not in domain and "http://" not in domain :
    new_domain = "https://" + domain

  else :
    new_domain = domain
  try :
    status_code , a_link , s_ , server_name = GET_DATA_WITH_LINK_FUNC(new_domain)
    get_data['domain'].append(new_domain)
    get_data['get_tex'].append(s_)

  except Exception as e :
    print(e)

HTTPSConnectionPool(host='a-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a0f829b0>: Failed to resolve 'a-msedge.net' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='amazonaws.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ba3a2103f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
'server'
HTTPSConnectionPool(host='root-servers.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a0ce5ab0>: Failed to resolve 'root-servers.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='akamai.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a10da6b0>: Failed to resolve 'akamai.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='akamaiedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a0ce6aa0>: Failed to resolve 'akamaiedge.net' ([Errno -5] No address associated with hostname)"))
'server'
'server'
'server'
HTTPSConnectionPool(host='googlevideo.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'googlevideo.com'. (_ssl.c:1007)")))
'server'
HTTPSConnectionPool(host='tiktokcdn.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a8c2aa0>: Failed to resolve 'tiktokcdn.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='windowsupdate.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a663d30>: Failed to resolve 'windowsupdate.com' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='akadns.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a69c730>: Failed to resolve 'akadns.net' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='microsoftonline.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a5723b0>: Failed to resolve 'microsoftonline.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='trafficmanager.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a5355d0>: Failed to resolve 'trafficmanager.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='gtld-servers.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a61bf10>: Failed to resolve 'gtld-servers.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='apple-dns.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a571720>: Failed to resolve 'apple-dns.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='l-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a619270>: Failed to resolve 'l-msedge.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='domaincontrol.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ba3a1a045e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPSConnectionPool(host='office.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a618a90>: Failed to resolve 'office.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='t-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39adfee90>: Failed to resolve 't-msedge.net' ([Errno -5] No address associated with hostname)"))
'server'
'server'
HTTPSConnectionPool(host='comcast.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ba39adff8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPSConnectionPool(host='aaplimg.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39adffa90>: Failed to resolve 'aaplimg.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='nflxso.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a3f7580>: Failed to resolve 'nflxso.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='cloudfront.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a3f7fa0>: Failed to resolve 'cloudfront.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='windows.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'windows.net'. (_ssl.c:1007)")))
HTTPSConnectionPool(host='gvt2.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a3f7e80>: Failed to resolve 'gvt2.com' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='s-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a3f7c40>: Failed to resolve 's-msedge.net' ([Errno -5] No address associated with hostname)"))
'server'
'server'
HTTPSConnectionPool(host='cdn77.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3d2c15630>: Failed to resolve 'cdn77.org' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='gvt1.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a0d2a70>: Failed to resolve 'gvt1.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='edgekey.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a8940a0>: Failed to resolve 'edgekey.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='wac-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39ae04c10>: Failed to resolve 'wac-msedge.net' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='bytefcdn-oversea.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39ae05570>: Failed to resolve 'bytefcdn-oversea.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='ytimg.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39fc4f1f0>: Failed to resolve 'ytimg.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='trbcdn.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'trbcdn.net'. (_ssl.c:1007)")))
'server'
HTTPSConnectionPool(host='e2ro.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a1a05660>: Failed to resolve 'e2ro.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='cdninstagram.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a1972860>: Failed to resolve 'cdninstagram.com' ([Errno -5] No address associated with hostname)"))
'server'
'server'
HTTPSConnectionPool(host='appsflyersdk.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a0f82dd0>: Failed to resolve 'appsflyersdk.com' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='macromedia.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ba3a0f80fa0>, 'Connection to macromedia.com timed out. (connect timeout=None)'))
'server'
'server'
HTTPSConnectionPool(host='a2z.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a2102b00>: Failed to resolve 'a2z.com' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='ttlivecdn.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a189f90>: Failed to resolve 'ttlivecdn.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='dnsowl.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a109bfd0>: Failed to resolve 'dnsowl.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='msedge.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ba3a1ec43a0>, 'Connection to msedge.net timed out. (connect timeout=None)'))
HTTPSConnectionPool(host='b-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a1ec5e40>: Failed to resolve 'b-msedge.net' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='edgesuite.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a170fa90>: Failed to resolve 'edgesuite.net' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='msftncsi.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39acaebf0>: Failed to resolve 'msftncsi.com' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='bytefcdn-ttpeu.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a101b9d0>: Failed to resolve 'bytefcdn-ttpeu.com' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='registrar-servers.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ba3a101b610>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPSConnectionPool(host='spo-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a1722a10>: Failed to resolve 'spo-msedge.net' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='ggpht.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a22d3e20>: Failed to resolve 'ggpht.com' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='2mdn.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a22d3c70>: Failed to resolve '2mdn.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='one.one', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1007)')))
HTTPSConnectionPool(host='rbxcdn.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a0ce4340>: Failed to resolve 'rbxcdn.com' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='adnxs.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a20dfe80>: Failed to resolve 'adnxs.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='mangosip.ru', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ba39a3f77c0>, 'Connection to mangosip.ru timed out. (connect timeout=None)'))
HTTPSConnectionPool(host='akamaized.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39fc79ea0>: Failed to resolve 'akamaized.net' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='rocket-cdn.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a3f7340>: Failed to resolve 'rocket-cdn.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='miit.gov.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a3f6170>: Failed to resolve 'miit.gov.cn' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='omtrdc.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a11a9960>: Failed to resolve 'omtrdc.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='o365filtering.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a3f63b0>: Failed to resolve 'o365filtering.com' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='aiv-cdn.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a20dd030>: Failed to resolve 'aiv-cdn.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='azurewebsites.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a8e1600>: Failed to resolve 'azurewebsites.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='netflix.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ba3a230ebc0>, 'Connection to netflix.net timed out. (connect timeout=None)'))
HTTPSConnectionPool(host='amazon.dev', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a1d74490>: Failed to resolve 'amazon.dev' ([Errno -5] No address associated with hostname)"))
'server'
'server'
HTTPSConnectionPool(host='demdex.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a919870>: Failed to resolve 'demdex.net' ([Errno -5] No address associated with hostname)"))
'server'
'server'
HTTPSConnectionPool(host='cloudapp.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a5c2410>: Failed to resolve 'cloudapp.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='wsdvs.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a5c1f00>: Failed to resolve 'wsdvs.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='tiktokcdn-us.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a170e2c0>: Failed to resolve 'tiktokcdn-us.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='akamaihd.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a170fdc0>: Failed to resolve 'akamaihd.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='cdn-apple.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a8c2200>: Failed to resolve 'cdn-apple.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='azureedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a11a90f0>: Failed to resolve 'azureedge.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='cisco.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)')))
HTTPSConnectionPool(host='3gppnetwork.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a45bd00>: Failed to resolve '3gppnetwork.org' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='dual-s-msedge.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a0df2b0>: Failed to resolve 'dual-s-msedge.net' ([Errno -5] No address associated with hostname)"))
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
HTTPSConnectionPool(host='edgecdn.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1007)')))
HTTPSConnectionPool(host='atomile.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a1a3bf40>: Failed to resolve 'atomile.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='shifen.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ba3a1099660>, 'Connection to shifen.com timed out. (connect timeout=None)'))
'server'
HTTPSConnectionPool(host='abusix.zone', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39a1209a0>: Failed to resolve 'abusix.zone' ([Errno -5] No address associated with hostname)"))

/usr/lib/python3.10/html/parser.py:170: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  k = self.parse_starttag(i)

'server'
'server'
HTTPSConnectionPool(host='samsungcloudsolution.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a10dada0>: Failed to resolve 'samsungcloudsolution.com' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='un.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)')))
HTTPSConnectionPool(host='allawnos.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a1e12830>: Failed to resolve 'allawnos.com' ([Errno -5] No address associated with hostname)"))
'server'
HTTPSConnectionPool(host='azurefd.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba39aa80310>: Failed to resolve 'azurefd.net' ([Errno -5] No address associated with hostname)"))
HTTPSConnectionPool(host='ksyuncdn.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a20faf20>: Failed to resolve 'ksyuncdn.com' ([Errno -5] No address associated with hostname)"))
'server'
'server'
HTTPSConnectionPool(host='liadm.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ba3a0f22dd0>: Failed to resolve 'liadm.com' ([Errno -5] No address associated with hostname)"))

KeyboardInterrupt:

In [21]:
len(get_data['domain'])

180

In [22]:
df1 = pd.DataFrame(get_data)

In [23]:
df1.to_csv('180_toal.csv' , index = False )

In [24]:
df1

                    domain                                            get_tex
0       https://google.com                © 2024 -Privacy-TermsPrivacy, Terms
1    https://microsoft.com
2        https://apple.com  Unbelievably thin. Incredibly powerful.Buy Mac...
3      https://youtube.com
4      https://twitter.com
..                     ...                                                ...
175        https://sapo.pt  As notícias, jornais e rádios locais, estão aq...
176     https://criteo.net
177   https://springer.com  With more than 2,900 journals and 300,000 book...
178     https://adform.net
179      https://quora.com  Something went wrong. Wait a moment and try ag...

[180 rows x 2 columns]